"""Add all test parameters to TestResult

Revision ID: 10040ce65f91
Revises: 
Create Date: 2025-06-14 17:01:40.451369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10040ce65f91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viscosity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('flash_point', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sulphur_content', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('octane_content', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('water_content', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('days_until_degradation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('storage_grade', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_column('storage_grade')
        batch_op.drop_column('days_until_degradation')
        batch_op.drop_column('water_content')
        batch_op.drop_column('octane_content')
        batch_op.drop_column('sulphur_content')
        batch_op.drop_column('flash_point')
        batch_op.drop_column('density')
        batch_op.drop_column('viscosity')

    # ### end Alembic commands ###
