"""Add degradation_factors column

Revision ID: 31c24d385f5f
Revises: 10040ce65f91
Create Date: 2025-06-15 23:51:55.946905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c24d385f5f'
down_revision = '10040ce65f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degradation_factors', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_column('degradation_factors')

    # ### end Alembic commands ###
